prodotto.selectByFilter = select p from Prodotto p \
where (:idCategoria is null or p.categoria.idCategoria = :idCategoria) \
and (:marca is null or lower(p.marca) like lower(concat('%', cast(:marca as string), '%'))) \
and (:nome is null or lower(p.nome) like lower(concat('%', cast(:nome as string), '%'))) \
order by p.nome asc

ordine.selectByFilter = select o from Ordine o \
where (:idUtente is null or o.utente.idUtente = :idUtente) \
and (:stato is null or o.stato = :stato) \
and (:statoPagamento is null or o.statoPagamento = :statoPagamento) \
order by o.dataOrdine desc
